#!/usr/bin/env ruby
system 'echo "Rails Best Practices" && rails_best_practices'
system 'echo "RuboCop" && rubocop --config ./config/rubocop.yml'
system 'echo "Reek" && reek -c ./config/reek.yml' 
system 'echo "Flog" && flog app'
system 'echo "Flay" && flay app'